"""create users table

Revision ID: 8ae96803c164
Revises: 2d9476096342
Create Date: 2025-12-25 01:44:17.741358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ae96803c164'
down_revision: Union[str, Sequence[str], None] = '2d9476096342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_seller_stats_average_rating'), table_name='seller_stats')
    op.drop_index(op.f('ix_seller_stats_id'), table_name='seller_stats')
    op.drop_index(op.f('ix_seller_stats_user_id'), table_name='seller_stats')
    op.drop_table('seller_stats')
    op.drop_index(op.f('ix_book_condition_scores_id'), table_name='book_condition_scores')
    op.drop_table('book_condition_scores')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_ratings_announcement_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_buyer_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_created_at'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_seller_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_new_rating', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_rating_reply', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_announcement_sold', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_low_rating_alert', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_account_suspended', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_message_received', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('app_notifications_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('notification_preferences_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ratings_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('announcement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('communication_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('condition_accuracy_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_speed_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('buyer_id <> seller_id', name='buyer_not_seller'),
    sa.CheckConstraint('communication_rating IS NULL OR communication_rating >= 1 AND communication_rating <= 5', name='comm_rating_range'),
    sa.CheckConstraint('condition_accuracy_rating IS NULL OR condition_accuracy_rating >= 1 AND condition_accuracy_rating <= 5', name='cond_rating_range'),
    sa.CheckConstraint('delivery_speed_rating IS NULL OR delivery_speed_rating >= 1 AND delivery_speed_rating <= 5', name='delivery_rating_range'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_range'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name='ratings_announcement_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='ratings_buyer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='ratings_seller_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ratings_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_ratings_seller_id'), 'ratings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_created_at'), 'ratings', ['created_at'], unique=False)
    op.create_index(op.f('ix_ratings_buyer_id'), 'ratings', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_ratings_announcement_id'), 'ratings', ['announcement_id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('books_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('authors', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cover_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preview_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('info_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('NEW_RATING', 'RATING_REPLY', 'ANNOUNCEMENT_SOLD', 'ANNOUNCEMENT_RESERVED', 'LOW_RATING_ALERT', 'ACCOUNT_SUSPENDED', 'ACCOUNT_REACTIVATED', 'MESSAGE_RECEIVED', 'PRICE_DROP', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('related_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_announcement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_rating_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_sent_email', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['related_announcement_id'], ['announcements.id'], name=op.f('notifications_related_announcement_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_rating_id'], ['ratings.id'], name=op.f('notifications_related_rating_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], name=op.f('notifications_related_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('book_condition_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_no_missing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('page_no_torn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('page_clean', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('page_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('binding_no_loose', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('binding_no_falling', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('binding_stable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('binding_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cover_no_detachment', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cover_clean', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cover_no_scratches', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cover_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('damage_no_burns', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('damage_no_smell', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('damage_no_insects', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('damage_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('accessories_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('accessories_content', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('accessories_extras', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('accessories_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('condition_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('base_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('suggested_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('has_photos', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ai_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('photo_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('book_condition_scores_announcement_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('book_condition_scores_pkey')),
    sa.UniqueConstraint('announcement_id', name=op.f('book_condition_scores_announcement_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_book_condition_scores_id'), 'book_condition_scores', ['id'], unique=False)
    op.create_table('seller_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_ratings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_communication', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_condition_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_delivery_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rating_5_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating_4_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating_3_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating_2_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating_1_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_top_seller', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('total_sales', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('seller_stats_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('seller_stats_pkey'))
    )
    op.create_index(op.f('ix_seller_stats_user_id'), 'seller_stats', ['user_id'], unique=True)
    op.create_index(op.f('ix_seller_stats_id'), 'seller_stats', ['id'], unique=False)
    op.create_index(op.f('ix_seller_stats_average_rating'), 'seller_stats', ['average_rating'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('market_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('final_calculated_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('condition', postgresql.ENUM('NEUF', 'COMME_NEUF', 'BON_ETAT', 'ETAT_ACCEPTABLE', 'USAGE', name='bookconditionenum'), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('INFORMATIQUE', 'MATHEMATIQUES', 'PHYSIQUE', 'CHIMIE', 'BIOLOGIE', 'MEDECINE', 'ECONOMIE', 'GESTION', 'DROIT', 'LANGUES', 'LITTERATURE', 'HISTOIRE', 'GEOGRAPHIE', 'PHILOSOPHIE', 'PSYCHOLOGIE', 'ARCHITECTURE', 'INGENIERIE', 'AUTRE', name='bookcategoryenum'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'VENDU', 'RESERVE', 'DESACTIVE', name='announcementstatusenum'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_images', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publication_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('announcements_book_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('announcements_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('announcements_pkey'))
    )
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('university', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
